<form method="post" action="<?= $block->getPostUrl() ?>">
    <fieldset>
        <div>
            <label for="first_name"><?= __("First Name") ?></label>
            <input type="text" name="first_name" id="first_name" />
        </div>
        <div>
            <label for="last_name"><?= __("Last Name") ?></label>
            <input type="text" name="last_name" id="last_name" />
        </div>
        <div>
            <label for="email_id"><?= __("Email Id") ?></label>
            <input type="text" name="email_id" id="email_id" />
        </div>
        <input type="submit" value="<?= __("Add Employee") ?>" />
    </fieldset>
</form>
<hr />